---
- name: Meraki deployment
  hosts: localhost
  vars:
    meraki_api_key: "{{ meraki_key }}"
    org_name: "{{ org_name }}"

  tasks:

    - name: Include variables for devices
      include_vars:
        file: ../vars/max/devices.yml
        name: devices

    - name: Include variables for addresses
      include_vars:
        file: addresses_notemplate.yml
        name: addresses

    - name: Create site network
      cisco.meraki.networks:
        meraki_api_key: "{{ meraki_api_key }}"
        organizationId: "{{ org_name }}"
        state: present
        name: "{{ item.value.network_name }}"
        productTypes:
          - switch
          - appliance
          - wireless
      register: off_network
      loop: "{{ lookup('dict', devices) }}"

    - name: Add devices to Network
      cisco.meraki.networks_devices_claim:
        meraki_api_key: "{{ meraki_api_key }}"
        networkId: "{{ off_network.results.0.meraki_response.id }}"
        serials: "{{ item.value.serial_no }}"
      register: off_add_dev1
      loop: "{{ lookup('dict', devices) }}"

    - name: Enable VLANs in the Network
      cisco.meraki.networks_appliance_vlans_settings:
        meraki_api_key: "{{ meraki_api_key }}"
        networkId: "{{ off_network.results.0.meraki_response.id }}"
        vlansEnabled: true
      register: off_enable_vlans
      loop: "{{ lookup('dict', addresses) }}"

    - name: Add subnets
      cisco.meraki.networks_appliance_vlans:
        meraki_api_key: "{{ meraki_api_key }}"
        networkId: "{{ off_network.results.0.meraki_response.id }}"
        state: present
        name: "{{ item.value.name }}"
        id: "{{ item.value.id }}"
        vlanId: "{{ item.value.vlanId }}"
        subnet: "{{ item.value.subnet }}"
        applianceIp: "{{ item.value.default_gw }}"
      register: off_add_subnets
      loop: "{{ lookup('dict', addresses) }}"
