# CICD 

name: CICD

on:
  push:
    branches: [ "main" ]
    paths: 'playbooks/vars/**'

jobs:
  lint: 
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@main
        with:
          path: 'playbooks/deploy-branch-readyaml.yaml'

      - shell: bash
        env:
          auth: ${{ secrets.MERAKIAPI }}
        run: sh ./scripts/entrypoint.sh
